#!/bin/bash

SCRIPT=${SCRIPT:-`realpath "$0"`}
GID=${GID:-`id -g $USER`}

NERF=false
IMAGE=
PASSTHRU=""

SUDOERS="/etc/sudoers"
PASSWD="/etc/passwd"

usage() {
    echo "usage"
    docker run --help
    echo "*********************************************************************"
    echo "usage: dock [-h] [--help, --nerf] image"
    exit 1
}

container() {
    groupadd --gid $GID $USER
    useradd --uid $UID --gid $GID --shell $SHELL --no-create-home $USER
    usermod -aG sudo $USER
    echo -e "\n%sudo   ALL=(ALL) NOPASSWD: ALL\n" > /etc/sudoers
    exec su - $USER
}

hostmachine() {
    volumes=()
    volumes+=($SCRIPT:$SCRIPT)
    volumes+=($HOME:$HOME)
    volumes=$(printf " -v %s" "${volumes[@]}")
    env="env PATH=$PATH HOME=$HOME USER=$USER UID=$UID GID=$GID SHELL=$SHELL SCRIPT=$SCRIPT"
    cmd="docker run $volumes $PASSTHRU -it $IMAGE $env $SCRIPT DOCKER_CONTAINER"
    if $NERF; then
        echo $cmd
    else
        exec $cmd
    fi
}

for item in "$@"; do
    case $item in
        -h|--help)
            usage
        ;;
        --nerf)
            NERF=true
        ;;
        *)
            if [ -n "$IMAGE" ]; then
                PASSTHRU="$PASSTHRU $IMAGE"
            fi
            IMAGE=$item
            shift 2
        ;;
    esac
done

if [ -z "$IMAGE" ]; then
    echo "missing value for IMAGE"
    usage
fi

if [ "$IMAGE" == "DOCKER_CONTAINER" ]; then
    container
else
    hostmachine
fi
